# Generated by Django 5.0.3 on 2024-04-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_order_rename_subcategory_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default='default_value', max_length=200),
        ),
    ]
