# Generated by Django 5.0.3 on 2024-04-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_subcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
