# Generated by Django 5.0.3 on 2024-04-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_subcategory_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='category_name',
        ),
    ]
