# Generated by Django 5.0.3 on 2024-04-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_orders_quantity_orders_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='subcategory',
            new_name='category_name',
        ),
    ]
