# Generated by Django 5.0.3 on 2024-04-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0007_rename_subcategory_orders_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
